CFLAGS += -Wall -g
all: testeFilaDePrioridade testeFilaCircular

testeFilaDePrioridade: testeFilaDePrioridade.c ../filaDePrioridade.c ../filaDePrioridade.h
testeFilaCircular: testeFilaCircular.c ../filaCircular.c ../filaCircular.h
